DROP TABLE MEM0;
CREATE TABLE MEMO(
	IDX NUMBER NOT NULL PRIMARY KEY,
	WRITER VARCHAR2(50) NOT NULL,
	MEMO VARCHAR2(200) NOT NULL,
	POST_DATE DATE DEFAULT SYSDATE
	);
	
INSERT INTO MEMO VALUES (1, 'KIM', '메모', SYSDATE);

SELECT * FROM MEMO;